# @format

name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: LearningOS message
        uses: Jack-Zhang-1314/OS_2022@v0.0.1
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.OS_2022 }}
        with:
          source_file: lab1-os3_${{github.actor}}.json
          destination_repo: 'os2edu/grading'
          destination_folder: 'src/data'
          user_email: 'zyj17715640603@gmail.com'
          user_name: 'Jack-Zhang-1314'
          commit_message: 'A custom message for the commit'
